name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Neovim
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:neovim-ppa/unstable
        sudo apt-get update
        sudo apt-get install -y neovim

    - name: Install Luarocks
      run: |
        sudo apt-get install -y luarocks

    - name: Install Busted
      run: |
        sudo luarocks install busted

    - name: Run tests
      run: |
        busted
